# Generated by Django 5.1.5 on 2025-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="registermodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.BigIntegerField()),
                ("password", models.CharField(max_length=30)),
                ("address", models.TextField()),
                ("gender", models.CharField(max_length=30)),
                ("role", models.CharField(max_length=10)),
                ("profilepicture", models.ImageField(upload_to="photos")),
            ],
        ),
    ]
